name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}
      - run: npx nx affected -t lint test build --parallel=3
